export const courses = [
  {
    id: 0,
    name: "HTML",
    price: 5,
    category: "front-end",
    featured: false,
  },
  {
    id: 1,
    name: "CSS",
    price: 10,
    category: "front-end",
    featured: false,
  },
  {
    id: 2,
    name: "JAVASCRIPT",
    price: 15,
    category: "front-end",
    featured: false,
  },
  {
    id: 3,
    name: "REACT",
    price: 20,
    category: "front-end",
    featured: true,
  },
  {
    id: 4,
    name: "REDUX",
    price: 5,
    category: "front-end",
    featured: false,
  },
  {
    id: 5,
    name: "PYTHON",
    price: 40,
    category: "back-end",
    featured: true,
  },
  {
    id: 6,
    name: "DJANGO",
    price: 60,
    category: "back-end",
    featured: true,
  },
  {
    id: 7,
    name: "DISECRETE MATH",
    price: 30,
    category: "others",
    featured: false,
  },
  {
    id: 8,
    name: "CALCULUS",
    price: 30,
    category: "others",
    featured: false,
  },
  {
    id: 9,
    name: "SQL",
    price: 10,
    category: "back-end",
    featured: false,
  },
  {
    id: 10,
    name: "GEOLOGY",
    price: 10,
    category: "others",
    featured: false,
  },
  {
    id: 11,
    name: "POLITICS",
    price: 20,
    category: "others",
    featured: false,
  },
  {
    id: 12,
    name: "STATISTICS",
    price: 5,
    category: "others",
    featured: false,
  },
  {
    id: 13,
    name: "MONGODB",
    price: 5,
    category: "back-end",
    featured: false,
  },
];
